// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebzvluscnbkolzbqajcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVienZsdXNjbmJrb2x6YnFhamNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NzY3NDgsImV4cCI6MjA2OTE1Mjc0OH0.ho0VNJ812Nar3ptWxDA000z92RxUkN6nPFCSnN4KdcA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});